# Generated by Django 3.0.7 on 2025-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0009_auto_20251201_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/g6.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
